import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "next/font/google";
import Footer from "@/components/footer";
import ReactQueryProvider from "./libs/QueryProvider";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = Manrope({subsets: ["latin"], weight:["400", "500", "800"]})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className}} antialiased`}
      >
        <ReactQueryProvider>
            <Header />
            <main className="flex min-h-screen flex-col gap-16 lg:px-24 lg:py-12 max-lg:py-10 max-lg:px-8 bg-white z-50">
              {children}
            </main>
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
